### PR TITLE
be-rust: Translate connected types more

### LINKED ISSUE #303: Rust translator crashes on StringBuilder property
```kt
$ class Hi(public builder: StringBuilder) {}
interactive#0: Hi__0
$ translate(0, "rust")
kotlin.NotImplementedError: An operation is not implemented: StringBuilder
	at lang.temper.be.rust.RustTranslator.translateTypeDefinition$be_rust(RustTranslator.kt:2913)
	at lang.temper.be.rust.RustTranslator.translateTypeNominal(RustTranslator.kt:2936)
	at lang.temper.be.rust.RustTranslator.translateType(RustTranslator.kt:2799)
	at lang.temper.be.rust.RustTranslator.translateType$default(RustTranslator.kt:2783)
	at lang.temper.be.rust.RustTranslator.translateFunctionDeclarationOrMethod(RustTranslator.kt:1806)
	at lang.temper.be.rust.RustTranslator.translateFunctionDeclarationOrMethod$default(RustTranslator.kt:1775)
	at lang.temper.be.rust.RustTranslator.translateGetter(RustTranslator.kt:1889)
	at lang.temper.be.rust.RustTranslator.translateMethodLike(RustTranslator.kt:2385)
	at lang.temper.be.rust.RustTranslator.translateMethodLike$default(RustTranslator.kt:2373)
	at lang.temper.be.rust.RustTranslator.processTypeDeclarationClass(RustTranslator.kt:670)
	at lang.temper.be.rust.RustTranslator.processTypeDeclaration(RustTranslator.kt:583)
	at lang.temper.be.rust.RustTranslator.processTopLevel(RustTranslator.kt:290)
	at lang.temper.be.rust.RustTranslator.translateModule(RustTranslator.kt:107)
	at lang.temper.be.rust.RustBackend.translate(RustBackend.kt:92)
```

Works fine for locals, though:

```rs
$ let hi(): Void { let builder: StringBuilder = new StringBuilder(); }
interactive#2: void
$ translate(2, "rust")
Translated rust for interactive#2
  interactive/
    src/
      i0002/
        mod.rs: text/rust
          #![allow(warnings)]
          use temper_core::AnyValueTrait;
          use temper_core::AsAnyValue;
          use temper_core::Pair;
          pub (crate) fn init() -> temper_core::Result<()> {
              static INIT_ONCE: std::sync::OnceLock<temper_core::Result<()>> = std::sync::OnceLock::new();
              INIT_ONCE.get_or_init(| |{
                      let return__6: () = ();
                      Ok(())
              }).clone()
          }
          pub fn hi() {
              let builder__3: std::sync::Arc<std::sync::RwLock<String>> = std::sync::Arc::new(std::sync::RwLock::new(String::new()));
          }
...
```

### PR DESCRIPTION
**Pull request by tjpalmer**
- Fix #303

### CODE REVIEW

File: be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustTranslator.kt [hunk 1]
```diff
@@ -2811,14 +2813,15 @@ class RustTranslator(
...
     private fun translateType(type: TmpL.AType, inExpr: Boolean = false, isFlex: Boolean = false) =
         translateType(type.ot, inExpr = inExpr, isFlex = isFlex)
 
     private fun translateType(type: TmpL.Type, inExpr: Boolean = false, isFlex: Boolean = false): Rust.Type {
         val pos = type.pos
         // Check first for connected types.
         ((type as? TmpL.NominalType)?.typeName as? TmpL.ConnectedToTypeName)?.let { typeName ->
-            return@translateType translateTypeConnected(pos, typeName)
+            return@translateType translateTypeConnected(pos, typeName.name)
         }
```
Comment (tjpalmer) [inline be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustTranslator.kt:2825]: I hadn't realized we sometimes need to handle other directions for connected types.

File: be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustTranslator.kt [hunk 2]
```diff
@@ -2910,7 +2913,11 @@ class RustTranslator(
                 WellKnownTypes.voidTypeDefinition,
                 -> OutName("()", def.name)
 
-                else -> TODO(def.name.displayName)
+                else -> TString.unpackOrNull(def.metadata[connectedSymbol]?.firstOrNull())?.let { key ->
+                    connectedTypes[key]?.let { typeName ->
+                        return@translateTypeDefinition translateTypeConnected(pos, typeName)
+                    }
+                } ?: TODO(def.name.displayName)
```
Comment (tjpalmer) [inline be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustTranslator.kt]: This should work for other connected types in the future, if needed.

File: functional-test-suite/src/commonMain/resources/types/string/build/build.temper.md [hunk 3]
```diff
@@ -53,3 +53,24 @@ Surrogate blocked.
...
+
+
+## StringBuilder property
+
+We hit an issue with properties of type StringBuilder on be-rust, so ensure it
+works.
+
+    class StringBuilderOwner(
+      public builder: StringBuilder,
+    ) {}
```
Comment (tjpalmer) [inline functional-test-suite/src/commonMain/resources/types/string/build/build.temper.md:65]: This failed before changes in this pr.

File: be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustSupportNetwork.kt [hunk 4]
```diff
@@ -1068,6 +1068,6 @@ private val connectedReferences = listOf(
 
 private const val FORMAT_MACRO_NAME = "format!"
 
-private val connectedTypes = mapOf(
+internal val connectedTypes = mapOf(
     "StringBuilder" to ConnectedType.StringBuilder,
 )
```
Comment (tjpalmer) [inline be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustSupportNetwork.kt:1073]: For access from translator.

File: be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustTranslator.kt [hunk 5]
```diff
@@ -2847,13 +2850,20 @@ class RustTranslator(
...
         }
     }
 
     internal fun translateTypeDefinition(def: TypeDefinition, pos: Position, isParam: Boolean = false): Rust.Type {
+        // First see if we have a connected type.
+        TString.unpackOrNull(def.metadata[connectedSymbol]?.firstOrNull())?.let { key ->
+            connectedTypes[key]?.let { typeName ->
+                return@translateTypeDefinition translateTypeConnected(pos, typeName)
+            }
+        }
```
Comment (tjpalmer) [inline be-rust/src/commonMain/kotlin/lang/temper/be/rust/RustTranslator.kt:2865]: I moved this up to the top because it's better for later extension this way, even if it only applies to StringBuilder right now.
