### PR TITLE
Test for watch build failures

### LINKED ISSUE #338: `temper watch` crashes on second build
This is rather new:

```kt
> temper watch -t py
Watch starting build #0 at 2026-02-17T17:38:52.737Z
Tests passed: 12 of 12
Finished build #0 in 15.626s
Watch starting build #1 at 2026-02-17T17:39:10.821Z
java.lang.IllegalStateException: Check failed.
        at lang.temper.frontend.staging.ModuleAdvancer.addModule(ModuleAdvancer.kt:198)
        at lang.temper.frontend.staging.ModuleAdvancer.createModule(ModuleAdvancer.kt:264)
        at lang.temper.frontend.staging.ModuleAdvancer.createModule$default(ModuleAdvancer.kt:246)
        at lang.temper.frontend.staging.SourceFilePartition.addModulesToAdvancer(SourceFilePartition.kt:382)
        at lang.temper.frontend.staging.ModuleAdvancerKt.buildStdModules(ModuleAdvancer.kt:918)
        at lang.temper.frontend.staging.ModuleAdvancerKt.access$buildStdModules(ModuleAdvancer.kt:1)
        at lang.temper.frontend.staging.ModuleAdvancer.advanceModules$lambda$13(ModuleAdvancer.kt:380)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:86)
        at lang.temper.frontend.staging.ModuleAdvancer$advanceModules$nonLocalLookup$1.lookup(ModuleAdvancer.kt:393)
        at lang.temper.frontend.staging.ImportHandler.invoke$lambda$2(ModuleAdvancer.kt:824)
        at lang.temper.frontend.staging.ImportHandler.invoke$applyExportStrategy(ModuleAdvancer.kt:812)
        at lang.temper.frontend.staging.ImportHandler.invoke(ModuleAdvancer.kt:824)
        at lang.temper.interp.Interpreter.dispatchCall$lambda$24(Interpreter.kt:1131)
        at lang.temper.interp.Interpreter.withMacroEnvironment(Interpreter.kt:2473)
        at lang.temper.interp.Interpreter.dispatchCall(Interpreter.kt:1130)
        at lang.temper.interp.Interpreter.access$dispatchCall(Interpreter.kt:162)
        at lang.temper.interp.Interpreter$ScopedMacroEnvironment.dispatchCallTo(Interpreter.kt:2329)
        at lang.temper.interp.importExport.ImportMacro.invoke(ImportMacro.kt:190)
        at lang.temper.interp.Interpreter.dispatchCall$lambda$24(Interpreter.kt:1131)
        at lang.temper.interp.Interpreter.withMacroEnvironment(Interpreter.kt:2473)
        at lang.temper.interp.Interpreter.dispatchCall(Interpreter.kt:1130)
        at lang.temper.interp.Interpreter.interpretCall(Interpreter.kt:1202)
        at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:372)
        at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:355)
        at lang.temper.interp.Interpreter.interpretTree$default(Interpreter.kt:349)
        at lang.temper.interp.Interpreter.interpretEdge$interp(Interpreter.kt:302)
        at lang.temper.interp.Interpreter.partiallyEvaluateDeclParts(Interpreter.kt:1345)
        at lang.temper.interp.Interpreter.interpretDecl(Interpreter.kt:1420)
        at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:373)
        at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:355)
        at lang.temper.interp.Interpreter.interpretTree$default(Interpreter.kt:349)
        at lang.temper.interp.Interpreter.interpretEdge$interp(Interpreter.kt:302)
        at lang.temper.interp.Interpreter.interpretBlock(Interpreter.kt:551)
        at lang.temper.interp.Interpreter.interpretBlock$default(Interpreter.kt:429)
        at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:371)
        at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:355)
        at lang.temper.interp.Interpreter.interpretReuseEnvironment(Interpreter.kt:290)
        at lang.temper.frontend.InterpretiveDanceStageKt.interpretiveDanceStage(InterpretiveDanceStage.kt:110)
        at lang.temper.frontend.importstage.ImportStage.process(ImportStage.kt:81)
        at lang.temper.frontend.Module.advance$lambda$26(Module.kt:456)
        at lang.temper.frontend.TopLevelBindings.whileSynchronized(TopLevelBindings.kt:93)
        at lang.temper.frontend.Module.advance(Module.kt:384)
        at lang.temper.frontend.staging.GroupOfModulesToAdvanceTogether.advanceModules$lambda$5(ModuleAdvancer.kt:642)
        at lang.temper.frontend.staging.ModuleAdvancerKt.withSnapshotter(ModuleAdvancer.kt:1180)
        at lang.temper.frontend.staging.ModuleAdvancerKt.access$withSnapshotter(ModuleAdvancer.kt:1)
        at lang.temper.frontend.staging.GroupOfModulesToAdvanceTogether.advanceModules(ModuleAdvancer.kt:641)
        at lang.temper.frontend.staging.ModuleAdvancer.advanceModules(ModuleAdvancer.kt:446)
        at lang.temper.frontend.staging.ModuleAdvancer.advanceModules(ModuleAdvancer.kt:362)
        at lang.temper.tooling.buildrun.BuildKt.stageLibraries(Build.kt:246)
        at lang.temper.tooling.buildrun.BuildKt.doOneBuild(Build.kt:319)
        at lang.temper.tooling.buildrun.Watcher.startBuild$lambda$21(Watcher.kt:251)
```

### PR DESCRIPTION
**Pull request by tjpalmer**
- Fix #338 (although just by rolling back part of #332)
- Clear out build results before builds
- Report watch build failures

### CODE REVIEW

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 1]
```diff
@@ -97,7 +98,10 @@ private fun runTest(
             ) { watcher ->
                 buildCount += 1
                 timer = Timer()
-                (watcher.lastBuildResult as? BuildDoneResult)?.sourceSnapshot?.also { snapshots.add(it) }
+                when (val result = watcher.lastBuildResult as? BuildDoneResult) {
+                    null -> failCount += 1
+                    else -> result.sourceSnapshot?.also { snapshots.add(it) }
+                }
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:104]: We expect build results when no failure for our constrained testing here.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 2]
```diff
@@ -117,6 +121,7 @@ private fun runTest(
         }
         assertTrue(ok, "expected ok.  output follows:\n\n$output")
         assertEquals(buildLimit, buildCount, "Build count wrong")
+        assertEquals(0, failCount, "Build failure")
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:124]: Failure before the rollback in ModuleAdvancer:

```kt
java.lang.IllegalStateException: Check failed.
	at lang.temper.frontend.staging.ModuleAdvancer.addModule(ModuleAdvancer.kt:198)
	at lang.temper.frontend.staging.ModuleAdvancer.createModule(ModuleAdvancer.kt:264)
	at lang.temper.frontend.staging.ModuleAdvancer.createModule$default(ModuleAdvancer.kt:246)
	at lang.temper.frontend.staging.SourceFilePartition.addModulesToAdvancer(SourceFilePartition.kt:382)
	at lang.temper.frontend.staging.ModuleAdvancerKt.buildStdModules(ModuleAdvancer.kt:918)
	at lang.temper.frontend.staging.ModuleAdvancerKt.access$buildStdModules(ModuleAdvancer.kt:1)
	at lang.temper.frontend.staging.ModuleAdvancer.advanceModules$lambda$13(ModuleAdvancer.kt:380)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:86)
	at lang.temper.frontend.staging.ModuleAdvancer$advanceModules$nonLocalLookup$1.lookup(ModuleAdvancer.kt:393)
	at lang.temper.frontend.staging.ImportHandler.invoke$lambda$2(ModuleAdvancer.kt:824)
	at lang.temper.frontend.staging.ImportHandler.invoke$applyExportStrategy(ModuleAdvancer.kt:812)
	at lang.temper.frontend.staging.ImportHandler.invoke(ModuleAdvancer.kt:824)
	at lang.temper.interp.Interpreter.dispatchCall$lambda$24(Interpreter.kt:1131)
	at lang.temper.interp.Interpreter.withMacroEnvironment(Interpreter.kt:2473)
	at lang.temper.interp.Interpreter.dispatchCall(Interpreter.kt:1130)
	at lang.temper.interp.Interpreter.access$dispatchCall(Interpreter.kt:162)
	at lang.temper.interp.Interpreter$ScopedMacroEnvironment.dispatchCallTo(Interpreter.kt:2329)
	at lang.temper.interp.importExport.ImportMacro.invoke(ImportMacro.kt:190)
	at lang.temper.interp.Interpreter.dispatchCall$lambda$24(Interpreter.kt:1131)
	at lang.temper.interp.Interpreter.withMacroEnvironment(Interpreter.kt:2473)
	at lang.temper.interp.Interpreter.dispatchCall(Interpreter.kt:1130)
	at lang.temper.interp.Interpreter.interpretCall(Interpreter.kt:1202)
	at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:372)
	at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:355)
	at lang.temper.interp.Interpreter.interpretTree$default(Interpreter.kt:349)
	at lang.temper.interp.Interpreter.interpretEdge$interp(Interpreter.kt:302)
	at lang.temper.interp.Interpreter.partiallyEvaluateDeclParts(Interpreter.kt:1345)
	at lang.temper.interp.Interpreter.interpretDecl(Interpreter.kt:1420)
	at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:373)
	at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:355)
	at lang.temper.interp.Interpreter.interpretTree$default(Interpreter.kt:349)
	at lang.temper.interp.Interpreter.interpretEdge$interp(Interpreter.kt:302)
	at lang.temper.interp.Interpreter.interpretBlock(Interpreter.kt:551)
	at lang.temper.interp.Interpreter.interpretBlock$default(Interpreter.kt:429)
	at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:371)
	at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:355)
	at lang.temper.interp.Interpreter.interpretReuseEnvironment(Interpreter.kt:290)
	at lang.temper.frontend.InterpretiveDanceStageKt.interpretiveDanceStage(InterpretiveDanceStage.kt:110)
	at lang.temper.frontend.importstage.ImportStage.process(ImportStage.kt:81)
	at lang.temper.frontend.Module.advance$lambda$26(Module.kt:456)
	at lang.temper.frontend.TopLevelBindings.whileSynchronized(TopLevelBindings.kt:93)
	at lang.temper.frontend.Module.advance(Module.kt:384)
	at lang.temper.frontend.staging.GroupOfModulesToAdvanceTogether.advanceModules$lambda$5(ModuleAdvancer.kt:642)
	at lang.temper.frontend.staging.ModuleAdvancerKt.withSnapshotter(ModuleAdvancer.kt:1180)
	at lang.temper.frontend.staging.ModuleAdvancerKt.access$withSnapshotter(ModuleAdvancer.kt:1)
	at lang.temper.frontend.staging.GroupOfModulesToAdvanceTogether.advanceModules(ModuleAdvancer.kt:641)
	at lang.temper.frontend.staging.ModuleAdvancer.advanceModules(ModuleAdvancer.kt:446)
	at lang.temper.frontend.staging.ModuleAdvancer.advanceModules(ModuleAdvancer.kt:362)
	at lang.temper.tooling.buildrun.BuildKt.stageLibraries(Build.kt:246)
	at lang.temper.tooling.buildrun.BuildKt.doOneBuild(Build.kt:319)
	at lang.temper.tooling.buildrun.Watcher.startBuild$lambda$21(Watcher.kt:252)
	at lang.temper.common.currents.UnmanagedFutureJvm.runLater$lambda$8(UnmanagedFuture.kt:103)
	at lang.temper.common.currents.UnmanagedFutureJvm.newComputedResultFutureImpl$lambda$0(UnmanagedFuture.kt:116)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
File system test failed.  To see the state of the files under test do

    cd C:\Users\work2\AppData\Local\Temp\temperrepeatWatchTest145748423467086106

expected ok.  output follows:

Watch starting build #0 at 2026-02-17T19:47:34.029Z
Finished build #0 in 14.268s
Watch starting build #1 at 2026-02-17T19:47:49.153Z
Finished build #1 in 109.436ms
Watcher reached build limit

org.opentest4j.AssertionFailedError: expected ok.  output follows:

Watch starting build #0 at 2026-02-17T19:47:34.029Z
Finished build #0 in 14.268s
Watch starting build #1 at 2026-02-17T19:47:49.153Z
Finished build #1 in 109.436ms
Watcher reached build limit

	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at kotlin.test.junit5.JUnit5Asserter.fail(JUnitSupport.kt:56)
	at kotlin.test.Asserter.assertTrue(Assertions.kt:694)
	at kotlin.test.junit5.JUnit5Asserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.Asserter.assertTrue(Assertions.kt:704)
	at kotlin.test.junit5.JUnit5Asserter.assertTrue(JUnitSupport.kt:30)
	at kotlin.test.AssertionsKt__AssertionsKt.assertTrue(Assertions.kt:44)
	at kotlin.test.AssertionsKt.assertTrue(Unknown Source)
	at lang.temper.cli.WatchTestKt.runTest$lambda$3(WatchTest.kt:122)
	at lang.temper.fs.RunWithTemporaryDirectoryKt.runWithTemporaryDirCopyOf$lambda$5(RunWithTemporaryDirectory.kt:78)
	at lang.temper.fs.RunWithTemporaryDirectoryKt.runWithTemporaryDirectory(RunWithTemporaryDirectory.kt:51)
	at lang.temper.fs.RunWithTemporaryDirectoryKt.runWithTemporaryDirCopyOf(RunWithTemporaryDirectory.kt:76)
	at lang.temper.cli.WatchTestKt.runTest(WatchTest.kt:78)
	at lang.temper.cli.WatchTestKt.access$runTest(WatchTest.kt:1)
	at lang.temper.cli.WatchTest.repeatWatchTest(WatchTest.kt:63)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

File: frontend/src/commonMain/kotlin/lang/temper/frontend/staging/ModuleAdvancer.kt [hunk 3]
```diff
@@ -1017,7 +1017,7 @@ private val sharedStdModulesMayNotRun = lazy {
         CustomValueFormatter.Nope,
     )
     val advancer = ModuleAdvancer(logSink)
-    buildStdModules(advancer, console, mayRun = true)
+    buildStdModules(advancer, console, mayRun = false)
```
Comment (tjpalmer) [inline frontend/src/commonMain/kotlin/lang/temper/frontend/staging/ModuleAdvancer.kt:1020]: Mike mentioned just rolling this back, but that might mean rolling back all the changes from #332. Might get other test failure here now?

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt [hunk 4]
```diff
@@ -236,6 +237,7 @@ class Watcher(
                 synchronized(this@Watcher) {
                     if (_lastBuildIndex == buildIndex) { // Still current
                         _currentBuild = build
+                        _lastBuildResult = null
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt:240]: This is before any build runs.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt [hunk 5]
```diff
@@ -281,10 +283,13 @@ class Watcher(
                         }
                     }
                 }
-            } finally {
-                // Signal done after the result is stored.
-                buildDone.completeOk(Unit)
+            } catch (e: Throwable) {
+                e.printStackTrace()
+                buildDone.completeError(e)
+                throw e
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt:289]: Nobody checks these errors yet, but for constrained situations like in WatchTest, we can at least check for null build result now.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt [hunk 6]
```diff
@@ -281,10 +283,13 @@ class Watcher(
...
             }
+            // Signal done after the result is stored.
+            buildDone.completeOk(Unit)
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt:292]: Technically could crash on printStackTrace above and miss completing the future. Should be low risk?

File: frontend/src/commonMain/kotlin/lang/temper/frontend/staging/ModuleAdvancer.kt (hunk 3 above)
Comment (tjpalmer) [reply frontend/src/commonMain/kotlin/lang/temper/frontend/staging/ModuleAdvancer.kt:1020]: Apparently it doesn't fail on other things with this change.
