### PR TITLE
Actually follow gitignore

### LINKED ISSUE #277: Ignore files better, can crash
We fail to ignore files already that are in `.gitignore`. Here's with some extra logging enabled:

```kt
PS C:\Users\work2\Documents\projects\hprof2db> cat .\.gitignore
ignore/
/target
PS C:\Users\work2\Documents\projects\hprof2db> ls

    Directory: C:\Users\work2\Documents\projects\hprof2db

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           11/7/2023  2:44 PM                .vscode
d----           4/18/2023  6:18 AM                ignore
d----           5/30/2025 10:21 AM                scripts
d----            1/8/2026  3:06 PM                src
d----           7/13/2023  5:32 AM                target
d----            1/8/2026  3:01 PM                temper.keep
d----            1/8/2026  3:11 PM                temper.out
-a---           5/30/2025 10:20 AM             16 .gitignore
-a---           4/17/2023  2:28 PM          10073 Cargo.lock
-a---           4/17/2023  2:28 PM            267 Cargo.toml
-a---           4/17/2023  2:34 PM            985 README.md

PS C:\Users\work2\Documents\projects\hprof2db> temper build
...
hey ---> -work/.git/refs/heads/more
hey ---> -work/.git/refs/remotes/origin/main
hey ---> -work/.git/refs/remotes/origin/more
hey ---> -work/.gitignore
hey ---> -work/Cargo.lock
hey ---> -work/Cargo.toml
hey ---> -work/ignore/burn.jfr
hey ---> -work/ignore/grouped-temper-values.txt
hey ---> -work/ignore/heap-a.sqlite3
Exception in thread "main" java.lang.OutOfMemoryError: Required array size too large
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3274)
        at lang.temper.fs.RealFileSystem.readBinaryFileContentSync(RealFileSystem.kt:184)
        at lang.temper.fs.FilteringFileSystemSnapshot.readFile(FilteringFileSystemSnapshot.kt:126)
        at lang.temper.fs.FilteringFileSystemSnapshot._init_$walk(FilteringFileSystemSnapshot.kt:91)
        at lang.temper.fs.FilteringFileSystemSnapshot._init_$walk(FilteringFileSystemSnapshot.kt:85)
        at lang.temper.fs.FilteringFileSystemSnapshot._init_$walk(FilteringFileSystemSnapshot.kt:85)
        at lang.temper.fs.FilteringFileSystemSnapshot.<init>(FilteringFileSystemSnapshot.kt:98)
        at lang.temper.tooling.buildrun.BuildKt.stageLibraries(Build.kt:202)
        at lang.temper.tooling.buildrun.BuildKt.doOneBuild(Build.kt:308)
        at lang.temper.tooling.buildrun.BuildKt.doBuild(Build.kt:157)
        at lang.temper.tooling.buildrun.BuildKt.doBuild$default(Build.kt:129)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$2.execute$lambda$0(Cli.kt:327)
        at lang.temper.cli.Main.wrapBuild(Cli.kt:771)
        at lang.temper.cli.Main.access$wrapBuild(Cli.kt:82)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$2.execute(Cli.kt:326)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at lang.temper.cli.Main.run(Cli.kt:755)
        at lang.temper.cli.Cli.main(Cli.kt:858)
PS C:\Users\work2\Documents\projects\hprof2db> ls ignore/heap-a.sqlite3

    Directory: C:\Users\work2\Documents\projects\hprof2db\ignore

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/18/2023  2:52 AM    19903238144 heap-a.sqlite3

PS C:\Users\work2\Documents\projects\hprof2db>
```

### PR DESCRIPTION
**Pull request by tjpalmer**
- Fix #277
- The failed case there worked for me after these changes
- Limit the scope there to better handling of a single ignore file and also ignoring `.git` dirs themselves
- Wrote up other issues for related matters
- This includes that this pr ignores the langserver

### CODE REVIEW

File: cli/src/main/kotlin/lang/temper/cli/DoWatch.kt [hunk 1]
```diff
@@ -25,7 +25,8 @@ internal fun doWatch(
     userSignalledDone: CompletableSignalRFuture,
     outDir: Path? = null,
     keepDir: Path? = null,
-    onEachBuildDone: (() -> Unit)? = null,
+    includeSnapshot: Boolean = false,
+    onEachBuildDone: ((Watcher) -> Unit)? = null,
```
Comment (tjpalmer) [inline cli/src/main/kotlin/lang/temper/cli/DoWatch.kt:39]: For better testing support. By default, snapshots aren't delivered up the chain.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 2]
```diff
@@ -76,17 +91,19 @@ private fun runTest(
                 buildLimit = buildLimit,
                 shellPreferences = shellPreferencesForTest(capturingConsole),
                 workRoot = dir,
-                ignoreFile = null,
+                ignoreFile = dir.resolve(".gitignore"),
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:94]: This is recognized by default if at the work root, but that's in Cli, not here.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 3]
```diff
@@ -64,7 +75,11 @@ private fun runTest(
     val userSignalledDone = UnmanagedFuture.newCompletableFuture<Unit, Nothing>(
         "User signalled done",
     )
-    runWithTemporaryDirCopyOf(testName, resourcePath("/testing/passing")) { dir ->
+    runWithTemporaryDirCopyOf(testName, resourcePath("/testing/passing"), subPath = Path("src")) { dir ->
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:78]: Put temper files under src so we can put other files elsewhere.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 4]
```diff
@@ -76,17 +91,19 @@ private fun runTest(
...
                 workRoot = dir,
-                ignoreFile = null,
+                ignoreFile = dir.resolve(".gitignore"),
                 userSignalledDone = userSignalledDone,
-            ) {
+                includeSnapshot = true,
+            ) { watcher ->
                 buildCount += 1
                 timer = Timer()
+                (watcher.lastBuildResult as? BuildDoneResult)?.sourceSnapshot?.also { snapshots.add(it) }
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:100]: Gather snapshots for later checking. We do this now on all WatchTest cases, but this shouldn't be the bottleneck of anything. There's only a few files being kept or ignored.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 5]
```diff
@@ -100,5 +117,77 @@ private fun runTest(
...
+    }
+}
+
+fun checkIgnored(snapshots: List<FileSystemSnapshot>) {
+    // Be thorough here.
+    val unwantedPaths = listOf(
+        dirPath("-work", ".git"),
+        // TODO Ignore unrelated files in the future, even if not explicitly ignored?
+        // filePath("-work", "above.txt"),
+        // dirPath("-work", "extra"),
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:161]: These are files we would ignore if we move forward with #278.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 6]
```diff
@@ -100,5 +117,77 @@ private fun runTest(
...
+        dirPath("-work", "src", "ignore"),
+        dirPath("-work", "target"),
+    )
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:164]: The three cases above that we do check for ignoring were all being included in snapshots before changes in this pr.

File: cli/src/test/kotlin/lang/temper/cli/WatchTest.kt [hunk 7]
```diff
@@ -100,5 +117,77 @@ private fun runTest(
...
+    // Wanted doesn't need to be exhaustive.
+    // This is mostly just a double-check that nobody changes paths generally on us.
+    val wantedPaths = listOf(
+        filePath("-work", "src", "test.temper"),
+    )
```
Comment (tjpalmer) [inline cli/src/test/kotlin/lang/temper/cli/WatchTest.kt:169]: I was afraid we could change something and then fail to find ignores for unrelated reasons.

File: fs-test-helpers/src/jvmMain/kotlin/lang/temper/fs/RunWithTemporaryDirectory.kt [hunk 8]
```diff
@@ -66,10 +66,15 @@ fun <T> runWithTemporaryDirectory(
...
+fun <T> runWithTemporaryDirCopyOf(
+    testName: String,
+    source: Path,
+    subPath: Path = Path.of(""),
+    testAction: (Path) -> T,
+): T {
     check(source.isDirectory())
     return runWithTemporaryDirectory(testName) { tempDir ->
-        copyRecursive(source, tempDir)
+        copyRecursive(source, tempDir.resolve(subPath))
```
Comment (tjpalmer) [inline fs-test-helpers/src/jvmMain/kotlin/lang/temper/fs/RunWithTemporaryDirectory.kt:77]: Added to support copying into a subdir of the temp dir.

File: fs/src/commonMain/kotlin/lang/temper/fs/FileFilterRules.kt [hunk 9]
```diff
@@ -26,7 +26,7 @@ interface FileFilterRules {
         override fun isIgnored(path: FilePath): Boolean {
             if (!pathToStrip.isAncestorOf(path)) { return false }
             return rules.isIgnored(
-                path.copy(segments = path.segments.subListToEnd(path.segments.size)),
+                path.copy(segments = path.segments.subListToEnd(pathToStrip.segments.size)),
```
Comment (tjpalmer) [inline fs/src/commonMain/kotlin/lang/temper/fs/FileFilterRules.kt:29]: This was just a bug that would always strip the whole path.

File: fs/src/commonMain/kotlin/lang/temper/fs/FileFilterRules.kt [hunk 10]
```diff
@@ -40,22 +40,21 @@ interface FileFilterRules {
...
-            a is Allow -> b
-            else -> ExcludeBoth(a, b)
+        fun anyIgnores(filters: List<FileFilterRules>): FileFilterRules = run {
+            val interestingFilters = filters.filter { it !is Allow }
+            when (interestingFilters.size) {
+                0 -> Allow
+                1 -> interestingFilters.first()
+                else -> ExcludeAll(interestingFilters)
+            }
         }
```
Comment (tjpalmer) [inline fs/src/commonMain/kotlin/lang/temper/fs/FileFilterRules.kt:50]: Felt like generalizing instead of laying multiple levels of eitherIgnores.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Build.kt [hunk 11]
```diff
@@ -287,6 +289,10 @@ private fun stageLibraries(
         libraryConfigurationsBundle,
         projectLogSink,
         priorBuildSuffices = priorBuildSuffices,
+        sourceSnapshot = when {
+            build.includeSnapshot -> sourceSnapshot
+            else -> null
+        },
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Build.kt:295]: Again, just an option for testing purposes.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt [hunk 12]
```diff
@@ -100,6 +100,7 @@ class BuildHarness(
     val workFileSystem = workFileSystem ?: RealFileSystem(workRoot, workDir)
 
     val filterRules: FileFilterRules = run {
+        // TODO Support multiple ignore files throughout tree.
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt:103]: Wrote up now as #280.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt [hunk 13]
```diff
@@ -108,8 +109,11 @@ class BuildHarness(
                     val filter = fromFile.result
                     val relPath = ignoreFileNorm.parent.relativize(workRoot).normalize()
 
-                    val parts = (0 until relPath.nameCount).map { i ->
-                        relPath.getName(i).name
+                    val parts = when {
+                        relPath.toString().isEmpty() -> listOf()
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt:113]: Empty path was seen as one segment of "", so we were always skipping common case top-level ignore files.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt [hunk 14]
```diff
@@ -149,7 +153,7 @@ class BuildHarness(
                             // just allow all files.
                             FileFilterRules.Allow
                         }
-                    }
+                    }.let { FileFilterRules.StripSegments(it, pathToStrip = workDir) }
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt:156]: And then we were failing to match rooted paths because the `-work/` prefix was preventing recognition.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt [hunk 15]
```diff
@@ -163,7 +167,9 @@ class BuildHarness(
         } else {
             FileFilterRules.Allow
         }
-        FileFilterRules.eitherIgnores(filterRulesFromFile, ExcludeOutputDirectories)
+        FileFilterRules.anyIgnores(
+            listOf(filterRulesFromFile, ExcludeOutputDirectories, ExcludeGitDirectory),
+        )
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/BuildHarness.kt:172]: Also ignore `.git/` every time. May could accommodate other source control systems in the future, but git is common, and we pretty much never need to look in there, and it can get big.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt [hunk 16]
```diff
@@ -198,7 +199,7 @@ class Watcher(
         }
 
         buildDone.thenDo("handle end of build #$buildIndex") {
-            onEachBuildDone?.let { it() }
+            onEachBuildDone?.let { it(this) }
```
Comment (tjpalmer) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt:202]: Providing this also provides access to the most recent build result.

File: tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt [hunk 17]
```diff
@@ -29,7 +29,8 @@ class Watcher(
     private val testBackends: List<BackendId>,
     private val moduleConfig: ModuleConfig = ModuleConfig.default,
     private val timeSource: TimeSource.WithComparableMarks = TimeSource.Monotonic,
-    private val onEachBuildDone: (() -> Unit)? = null,
+    private val onEachBuildDone: ((Watcher) -> Unit)? = null,
+    private val includeSnapshot: Boolean = false,
```
Comment (mikesamuel) [inline tooling/src/commonMain/kotlin/lang/temper/tooling/buildrun/Watcher.kt]: Is this something that should be true in production?

File: cli/src/main/kotlin/lang/temper/cli/DoWatch.kt [hunk 18]
```diff
@@ -25,7 +25,8 @@ internal fun doWatch(
     userSignalledDone: CompletableSignalRFuture,
     outDir: Path? = null,
     keepDir: Path? = null,
-    onEachBuildDone: (() -> Unit)? = null,
+    includeSnapshot: Boolean = false,
```
Comment (mikesamuel) [inline cli/src/main/kotlin/lang/temper/cli/DoWatch.kt:33]: Could we have a comment here saying more information gets sent out so that tests can check properties of it, but that it shouldn't affect semantics.

Assuming that's true.

File: cli/src/main/kotlin/lang/temper/cli/DoWatch.kt (hunk 1 above)
Comment (mikesamuel) [reply cli/src/main/kotlin/lang/temper/cli/DoWatch.kt:39]: Let's have a comment there.  Something like, the Watcher is provided so that test code has it, but it shouldn't be recursively invoked in a mutating way.

**Review by mikesamuel — APPROVED** [review]
